const cardContents = [
    { id: 1,title: 'Accenture', description: 'Position: Junior Data Scientist, Location: Bengaluru,Salary: 15 LPA, Experience: 0-2 years', imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/6d/Accenture_Logo.png", applyLink: "https://www.accenture.com/in-en/careers/jobdetails?id=ATCI-4373965-S1772953_en&title=Junior%20Data%20Scientist" },
    { id: 2,title: 'Capgemini', description: 'Position: JavaScript Developer, Location: Hyderabad, Salary: 10 LPA, Experience: 1-3 years', imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a6/Capgemini_logo.svg", applyLink: "https://www.capgemini.com/careers/" },
    { id: 3,ttitle: 'Tata Consultancy Services (TCS)', description: 'Position: Web Developer, Location: Pune, Salary: 12 LPA, Experience: 2-4 years', imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/44/TCS_logo.svg", applyLink: "https://www.tcs.com/careers" },
    { id: 4,ttitle: 'Infosys', description: 'Position: Machine Learning Engineer, Location: Chennai, Salary: 18 LPA, Experience: 3-5 years', imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/46/Infosys_logo.svg", applyLink: "https://www.infosys.com/careers" },
    { id: 5,ttitle: 'Wipro', description: 'Position: Data Scientist, Location: Bangalore, Salary: 20 LPA, Experience: 2-3 years', imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a5/Wipro_logo.png", applyLink: "https://www.wipro.com/careers/" },
    { id: 6,ttitle: 'Cognizant', description: 'Position: Software Engineer, Location: Mumbai, Salary: 14 LPA, Experience: 1-3 years', imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5e/Cognizant_logo.svg", applyLink: "https://www.cognizant.com/careers" },
    { id: 7,ttitle: 'HCL Technologies', description: 'Position: Full Stack Developer, Location: Noida, Salary: 16 LPA, Experience: 3-5 years', imageUrl: "https://upload.wikimedia.org/wikipedia/commons/6/68/HCL_Technologies_logo.png", applyLink: "https://www.hcltech.com/careers" },
    { id: 8,ttitle: 'Tech Mahindra', description: 'Position: Cloud Solutions Architect, Location: Delhi, Salary: 22 LPA, Experience: 5+ years', imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/ab/Tech_Mahindra_Logo.png", applyLink: "https://www.techmahindra.com/careers/" },
    { id: 9,ttitle: 'IBM', description: 'Position: Cloud Engineer, Location: Bengaluru, Salary: 25 LPA, Experience: 4-6 years', imageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/94/IBM_logo.svg", applyLink: "https://www.ibm.com/careers" },
    { id: 10,ttitle: 'Oracle', description: 'Position: Database Administrator, Location: Hyderabad, Salary: 20 LPA, Experience: 3-5 years', imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/1d/Oracle_logo.svg", applyLink: "https://www.oracle.com/corporate/careers/" },
    { id: 11,ttitle: 'Microsoft', description: 'Position: Software Engineer, Location: Redmond, USA, Salary: 30 LPA, Experience: 5+ years', imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a0/Microsoft_logo.svg", applyLink: "https://careers.microsoft.com/" },
    { id: 12,ttitle: 'Google', description: 'Position: Cloud Engineer, Location: Mountain View, USA, Salary: 35 LPA, Experience: 6+ years', imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/42/Google_2015_logo.svg", applyLink: "https://careers.google.com/jobs/" },
    { id: 13,ttitle: 'Amazon', description: 'Position: Data Analyst, Location: Seattle, USA, Salary: 28 LPA, Experience: 4-6 years', imageUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Amazon_logo.svg", applyLink: "https://www.amazon.jobs/en/" },
    { id: 14,ttitle: 'SAP', description: 'Position: SAP Developer, Location: Walldorf, Germany, Salary: 26 LPA, Experience: 3-5 years', imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/5e/SAP_2011_logo.svg", applyLink: "https://www.sap.com/about/careers.html" },
    { id: 15,ttitle: 'Salesforce', description: 'Position: Business Analyst, Location: San Francisco, USA, Salary: 32 LPA, Experience: 4-6 years', imageUrl: "https://upload.wikimedia.org/wikipedia/commons/4/44/Salesforce_logo.svg", applyLink: "https://www.salesforce.com/company/careers/" }
];
